### PR TITLE
CC License

### PR DESCRIPTION
**Pull request by ghost**
Added license.

### CODE REVIEW

**Comment by lee2sman** [comment]
Hi @tycap this isn't a license for code but for creative works. Can you look at some of the licenses at [choose a license](https://choosealicense.com/) and see if there's one there that does similar?

**Review by lee2sman — CHANGES_REQUESTED** [review]
Please change to a non creative-commons license

**Comment by lee2sman** [comment]
Thanks! Since you're finished, can you add README.md file to our repo and add a credits section and put a line that lists the license name there too?

**Comment by ghost** [comment]
Yes. I may hold off on the description until we are all finished.

**Pull request merged**
